In [1]:
import numpy as np

In [2]:
import h5py

### Understand the basic Image Classification pipeline and the data-driven approach (train/predict stages)

In [3]:
data = h5py.File("SVHN_single_grey1.h5")

In [4]:
list(data)

['X_test', 'X_train', 'X_val', 'y_test', 'y_train', 'y_val']

### Data fetching and understand the train/val/test splits.

In [5]:
x_test = data['X_test']

In [6]:
x_train = data['X_train']

In [7]:
y_test = data['y_test']

In [8]:
y_train = data['y_train']

In [9]:
x_val = data['X_val']

In [10]:
y_val = data['y_val']

In [11]:
x_test.shape

(18000, 32, 32)

In [12]:
x_train.shape

(42000, 32, 32)

In [13]:
x_val.shape

(60000, 32, 32)

In [14]:
y_train.shape

(42000,)

In [15]:
y_test.shape

(18000,)

In [16]:
y_val.shape

(60000,)

### Implement and apply an optimal k-Nearest Neighbor (kNN) classifier (7.5 points)

In [17]:
train_data = np.reshape(x_train,(42000,32*32))

In [18]:
test_data = np.reshape(x_test,(18000,32*32))

In [19]:
train_data.shape

(42000, 1024)

In [20]:
test_data.shape

(18000, 1024)

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
model = KNeighborsClassifier(n_neighbors=15)

In [23]:
# Train the model
model.fit(train_data, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=15, p=2,
           weights='uniform')

In [24]:
prediction = model.predict(test_data)

### Print the classification metric report (2.5 points)

In [25]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [26]:
print("Accuracy:", metrics.accuracy_score(prediction,y_test))

Accuracy: 0.5235555555555556


In [27]:
print("Confusion Metrix:   \n", metrics.confusion_matrix(prediction,y_test))

Confusion Metrix:   
 [[1233   95  100  136  117  163  318   98  249  335]
 [  68 1335  215  251  247  164  122  227  115  137]
 [  39   70  992  136   41   62   38  116   62   70]
 [  39   83  107  734   60  268   72   84  119   92]
 [  51   75   55   50 1182   63  129   26  100   65]
 [  46   34   30  160   14  683  128   35  120  108]
 [ 113   32   37   42   54  156  741   35  253   56]
 [  37   51  138   54   17   31   23 1116   28   69]
 [  86   21   54   98   34  114  210   30  655  119]
 [ 102   32   75   58   46   64   51   41  111  753]]


In [28]:
cr=metrics.classification_report(y_test,prediction)
print(cr)

              precision    recall  f1-score   support

           0       0.43      0.68      0.53      1814
           1       0.46      0.73      0.57      1828
           2       0.61      0.55      0.58      1803
           3       0.44      0.43      0.43      1719
           4       0.66      0.65      0.66      1812
           5       0.50      0.39      0.44      1768
           6       0.49      0.40      0.44      1832
           7       0.71      0.62      0.66      1808
           8       0.46      0.36      0.41      1812
           9       0.56      0.42      0.48      1804

   micro avg       0.52      0.52      0.52     18000
   macro avg       0.53      0.52      0.52     18000
weighted avg       0.53      0.52      0.52     18000



### Implement and apply a deep neural network classifier including (feedforward neural network, RELU activations) (5 points)

In [29]:
import tensorflow as tf

In [30]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

In [31]:
#Reshape data from 2D to 1D -> 32X32 to 1024
model.add(tf.keras.layers.Reshape((1024,),input_shape=(32,32)))

### Implement batch normalization for training the neural network (2.5 points)

In [32]:
#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

Instructions for updating:
Colocations handled automatically by placer.


In [33]:
model.add(tf.keras.layers.Dense(200, activation='relu'))
model.add(tf.keras.layers.Dense(100, activation='relu'))

In [34]:
#Output layer
model.add(tf.keras.layers.Dense(10, activation='softmax', name='Output'))

### Understand and be able to implement (vectorized) backpropagation (cost stochastic gradient descent, cross entropy loss, cost functions) (2.5 points)

In [35]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

### Understand the differences and trade-offs between traditional and NN classifiers with the help of classification metrics (5 points)

Change train and test labels into one-hot vectors¶

In [36]:
trainY = tf.keras.utils.to_categorical(y_train, num_classes=10)
testY = tf.keras.utils.to_categorical(y_test, num_classes=10)

In [37]:
x_test.shape

(18000, 32, 32)

In [38]:
x_train.shape

(42000, 32, 32)

In [39]:
x_val.shape

(60000, 32, 32)

In [40]:
#Train the model
features_val_arr = np.array(x_test)
model.fit(x_train,trainY,          
          validation_data=(features_val_arr, testY),
          epochs=30,
          batch_size=100,validation_split = 0.01,
         shuffle='batch')

Train on 42000 samples, validate on 18000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/30
42000/42000 [==============================] - 16s 391us/sample - loss: 2.0406 - acc: 0.3003 - val_loss: 1.6598 - val_acc: 0.4977
Epoch 2/30
42000/42000 [==============================] - 5s 118us/sample - loss: 1.4433 - acc: 0.5698 - val_loss: 1.2353 - val_acc: 0.6418
Epoch 3/30
42000/42000 [==============================] - 4s 106us/sample - loss: 1.1613 - acc: 0.6587 - val_loss: 1.0577 - val_acc: 0.6944
Epoch 4/30
42000/42000 [==============================] - 5s 110us/sample - loss: 1.0247 - acc: 0.6976 - val_loss: 0.9621 - val_acc: 0.7221
Epoch 5/30
42000/42000 [==============================] - 6s 132us/sample - loss: 0.9372 - acc: 0.7235 - val_loss: 0.8964 - val_acc: 0.7384
Epoch 6/30
42000/42000 [==============================] - 4s 107us/sample - loss: 0.8712 - acc: 0.7417 - val_loss: 0.8556 - val_acc: 0.7523
Epoch 7/30
42000/42000 [==============================] - 5s 

In [41]:
loss_and_metrics = model.evaluate(x_test, testY)
print(loss_and_metrics)

18000/18000 [==============================] - 2s 96us/sample - loss: 0.5889 - acc: 0.83920s - loss: 0.5828 - acc: 0.8
[0.5889296860694885, 0.8392222]


In [42]:
y_predict=model.predict_classes(x_test)

In [43]:
cr=metrics.classification_report(y_test,y_predict)
print(cr)

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      1814
           1       0.84      0.86      0.85      1828
           2       0.88      0.83      0.86      1803
           3       0.80      0.78      0.79      1719
           4       0.86      0.87      0.87      1812
           5       0.81      0.85      0.83      1768
           6       0.87      0.81      0.84      1832
           7       0.87      0.88      0.88      1808
           8       0.82      0.80      0.81      1812
           9       0.80      0.83      0.82      1804

   micro avg       0.84      0.84      0.84     18000
   macro avg       0.84      0.84      0.84     18000
weighted avg       0.84      0.84      0.84     18000



From the classification report for convectional KNN and Neural Network we can see that KNN has very low accuracy score and very low F1 score for each category. The reason is KNN does not learn from the provided feature and tries to classify with the help of distance formulas. In Neural networks, the hidden layers learn the image features by adjusting the weights and is able to classify better than convectional models. This is evident from F1 score for each labels for Neural networks.